### ISSUE TITLE
X-Frame-Options header is not included

### ISSUE THREAD

**Issue by snadon** [luckyframework/authentic#11]
X-Frame-Options header is not included in the HTTP response to protect against ’ClickJacking’ attacks.

**Comment by paulcsmith** [comment]
@joeldrapper this one would be handled in the main Lucky repo. I imagine this one and the other would all be part of a single SecureBrowserHeaders handler in Lucky

**Comment by paulcsmith** [comment]
Closing in favor of https://github.com/luckyframework/lucky/issues/565
