### ISSUE TITLE
Can't merge CLI pull request until a new release of Authentic

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/authentic#19]
This PR https://github.com/luckyframework/lucky_cli/pull/256 is failing because when it generates a new lucky app, the app loads the 0.1.0 release of Authentic. This release doesn't have the updated cookie stuff introduced in #16

Either a new version of authentic needs to be released, or we point lucky_cli to a specific commit of authentic.

Not urgent, but putting this here so we don't forget.

**Comment by paulcsmith** [comment]
Thanks! I think in the meantime Lucky CLI can use the master branch of authentic. We can bump and release a new version of authentic once we're ready for a new Lucky release. What do you think of that plan?

**Comment by edwardloveall** [comment]
Yup, that's pretty much what I assumed we'd do. 👍 I'm not going to add a dependency or anything because I don't want to forget and have Lucky ship pointing toward master on authentic.

**Comment by paulcsmith** [comment]
Closed by 
https://github.com/luckyframework/lucky_cli/pull/257
