### ISSUE TITLE
JWT Authentication

### ISSUE THREAD

**Issue by ld100** [luckyframework/authentic#24]
I'm going to use Lucky (and Authentic as a part of it ) for a small API-only project, that issues JWT tokens for users as a response to password authentication and also allows authentication by JWT for other actions.

Could you please suggest what is the best way to implement JWT auth according to Authentic ideology/architecture? Would it also help if I'll contribute this stuff back to Authentic once ready?

**Comment by jwoertink** [comment]
This is now added in as of https://github.com/luckyframework/lucky_cli/pull/395
