### ISSUE TITLE
Make the sign-in key configurable

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/authentic#62]
https://github.com/luckyframework/authentic/blob/110d4291362eec24e86094846c3eb0a12717f674/src/authentic/action_helpers.cr#L3

We could move this to a habitat setting, and just default the value to "user_id". This would be to avoid any case where maybe you want to set a `user_id` value in session in your app, but then you log your users out because of it. In that case,  you could change this key.

/cc. @paulcsmith

**Comment by paulcsmith** [comment]
Yeah I think Habitat configurable key with a default `"user_id"` makes sense!
